SuperB/urls.py
from django.contrib import admin
from django.conf import settings  
from django.conf.urls.static import static  
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('',include('account.api.urls')),
    path('',include('product.api.urls')),
    path('',include('checkout.api.urls')),
]


urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path('', include('account.urls')),
    path('', include('checkout.urls')),
    path('', include('core.urls')),
    path('', include('product.urls')),
)
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

checkout/api/urls.py
from .views import BasketAPIView,BasketItemAPIView
from django.urls import path


urlpatterns= [
    path('api/basket/', BasketAPIView.as_view(),name='basket'),
    path('api/basketitem/', BasketItemAPIView.as_view(),name='basketitem'),
    path('api/basketitem/<int:pk>/', BasketItemAPIView.as_view(),name='basketitem'),

]

checkout/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('checkout_billing_info/', views.CheckoutBillling.as_view(), name='checkout_billing_info'),
    path('checkout/', views.checkout, name='checkout'),
    path('shopping_cart/', views.shopping_cart, name='shopping_cart'),
    path('wishlist/',views.WishlistView.as_view(), name='wishlist'),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('error/', views.error, name='error'),
    path('faq/', views.faq, name='faq'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact_information/', views.contact_information, name='contact_information'),
    path('address_book/', views.address_book, name='address_book'),
    path('contact_us/', views.contact_us, name='contact_us'),
    # path('export_view/', views.export_view, name='export_view'),
]

checkout/models.py
from django.db import models
from django.contrib.auth import get_user_model
from product.models import Product
from django.forms import DecimalField
from phonenumber_field.modelfields import PhoneNumberField
USER = get_user_model()






class Order(models.Model):
    user            =  models.ForeignKey(USER, on_delete=models.CASCADE)
    status          =  models.CharField(max_length=255)
    basket          =  models.ForeignKey('Basket', on_delete=models.SET_NULL, null=True) 
    total_price     =  DecimalField(max_digits = 5,decimal_places = 2)
    checkout_adress =  models.ForeignKey('CheckoutMethod', on_delete=models.SET_NULL, blank=True, null=True)

    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return f"{self.status} - {self.basket} - {self.total_price}"


class Basket(models.Model):
    user = models.ForeignKey(USER, on_delete=models.CASCADE,related_name='basketofuser') 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return f"{self.user} - {self.created_at} - {self.updated_at}"


class BasketItem(models.Model):
    basket = models.ForeignKey("Basket", on_delete=models.CASCADE) 
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0.0)
    product_property_values_ids = models.ForeignKey("product.ProductPropertieValue", on_delete=models.CASCADE, null=True, blank=True) 
    product = models.ForeignKey("product.Product", on_delete=models.CASCADE) 
    quantity = models.IntegerField(default=1)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return f"{self.basket} - {self.price} - {self.product_property_values_ids} - {self.product}"





class Wishlist(models.Model):
    user     =     models.OneToOneField(USER, on_delete=models.CASCADE, null=True, blank=True, related_name="wishlistofUser")
    product  =     models.ManyToManyField(Product, related_name="wishlist_products")

    def __str__(self):
        return f"{self.user}'s Wishlist"


class CheckoutMethod(models.Model):
    user        =  models.OneToOneField(USER, on_delete=models.CASCADE, null=True, blank=True)
    first_name  =  models.CharField(max_length=50)
    last_name   =  models.CharField(max_length=50)
    address     =  models.CharField(max_length=50)
    city        =  models.CharField(max_length=50)
    country     =  models.CharField(max_length=50)
    zipcode     =  models.CharField(max_length=50)
    phone       =  PhoneNumberField(null=False, blank=False,unique=True)

    def __str__(self):
        return self.first_name


class ChecoutBilling(models.Model):
    user        = models.ForeignKey(USER, on_delete=models.CASCADE, null=True, blank=True)

    first_name  = models.CharField(max_length=50)
    last_name   = models.CharField(max_length=50)
    address     = models.CharField(max_length=100)
    city        = models.CharField(max_length=50)
    zipcode     = models.CharField(max_length=50)
    country     = models.CharField(max_length=50)
    phone       = PhoneNumberField(blank=True, null=True)

    def __str__(self):
        return self.address

checkout/forms.py
from django import forms
from django.forms import widgets
from checkout.models import CheckoutMethod, ChecoutBilling

class CheckoutForms(forms.ModelForm):

    class Meta:
        model = CheckoutMethod
        fields = [
            'user',
            'first_name',
            'last_name',
            'address',
            'city',
            'zipcode',
            'country',
            'phone',
 ]

        widgets = {
            'user': widgets.Select(attrs={'class': 'form-control'}),
            'first_name': widgets.TextInput(attrs={'class': 'input-text'}),
            'last_name': widgets.TextInput(attrs={'class': 'input-text'}),
            'address': widgets.TextInput(attrs={'class': 'input-text'}),
            'city': widgets.TextInput(attrs={'class': 'input-text'}),
            'zipcode': widgets.TextInput(attrs={'class': 'input-text'}),
            'country': widgets.TextInput(attrs={'class': 'input-text'}),
            'phone': widgets.TextInput(attrs={'class': 'input-text'}),
        }


class CheckoutBillingForms(forms.ModelForm):

     class Meta:
        model = ChecoutBilling
        fields = [
            'user',
            'first_name',
            'last_name',
            'address',
            'city',
            'zipcode',
            'country',
            'phone',]

        widgets = {
            'user' : widgets.Select(attrs={'class': 'form-control'}),
            'first_name': widgets.TextInput(attrs={'class': 'input-text'}),
            'last_name': widgets.TextInput(attrs={'class': 'input-text'}),
            'address': widgets.TextInput(attrs={'class': 'input-text'}),
            'city': widgets.TextInput(attrs={'class': 'input-text'}),
            'zipcode': widgets.TextInput(attrs={'class': 'input-text'}),
            'country': widgets.TextInput(attrs={'class': 'input-text'}),
            'phone': widgets.TextInput(attrs={'class': 'input-text'}),
        }

checkout/api/views.py
from rest_framework.generics import ( ListCreateAPIView)
from .serializers import BasketSerializer,BasketItemSerializer
from django.views.generic.detail import DetailView
from checkout.models import Basket, BasketItem
from django.contrib.auth import get_user_model

USER = get_user_model()


class GenericAPIViewSerializerMixin:


    def get_serializer_class(self):
        return self.serializer_classes[self.request.method]
      



class BasketAPIView(GenericAPIViewSerializerMixin,ListCreateAPIView,DetailView):
    queryset = Basket.objects.all()
   
    serializer_classes = {
        'GET': BasketSerializer,
        'POST': BasketSerializer,
    }
        



class GenericAPIViewSerializerMixin:


    def get_serializer_class(self):
        return self.serializer_classes[self.request.method]
      



class BasketItemAPIView(GenericAPIViewSerializerMixin,ListCreateAPIView,DetailView):
    queryset = BasketItem.objects.all()
   
    serializer_classes = {
        'GET': BasketItemSerializer,
        'POST': BasketItemSerializer,
        'DELETE': BasketItemSerializer,
    }
        

checkout/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from checkout.models import BasketItem 
from core.forms import SubscriberForm
from checkout.models import CheckoutMethod, Wishlist
from django.views.generic.list import ListView
from checkout.forms import CheckoutForms,CheckoutBillingForms
from checkout.models import Basket,Order
from django.http.response import HttpResponseRedirect
from django.views.generic.base import View



class CheckoutBillling(View):
    template_name = 'checkout_billing_info.html'
    http_method_names = ['get', 'post']


    def get(self, request):
        form = CheckoutBillingForms()
        return render(request, self.template_name, {'form': form})
    
    def post(self, request):
        form = CheckoutBillingForms(request.POST)
        if form.is_valid():
            form.save()
            order = Order.objects.create(
                user=request.user,
                basket = Basket.objects.get(user=request.user),
                checkout_adress = CheckoutMethod.objects.get(user=request.user),
                ordered = False
            )
            order.save()
            return redirect(reverse_lazy('shoping_cart'))
        else:
            return render(request, 'checkout_billing_info.html', {'form': form})



def checkout(request):
    form = CheckoutForms()

    if request.method == 'POST':
        form = CheckoutForms(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('checkout_billing_info'))
    context = {
        'form' : form,
        }
    return render(request, 'checkout.html',context)





def shopping_cart(request):
    form = SubscriberForm()
    basketitems = BasketItem.objects.all()
    totalprice = 0
    for item in basketitems:
        totalprice += item.product.price * item.quantity
    if request.method == 'POST':
        form = SubscriberForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('home'))
    context = {
        'form' : form,
        'basketitems' : basketitems,
        'totalprice' : totalprice
    }
    return render(request, 'shopping_cart.html',context)

def wishlist(request):
    form = SubscriberForm()
    if request.method == 'POST':
        form = SubscriberForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('home'))
    context = {
        'form' : form
    }
    return render(request, 'wishlist.html',context)



class WishlistView(ListView):
    model = Wishlist
    template_name = 'wishlist.html'
    quesyset =  Wishlist.objects.all()
    context_object_name = 'wishlist'

checkout/templates/checkout.html
{% extends 'base.html' %}
{% load static %}


<!-- CSS Style -->
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/internal.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'css/flexslider.css' %}">
{% endblock css %}


  
  {% block content %}
  <!-- Main Container -->
  <section class="main-container col2-right-layout bounceInUp animated">
    <div class="main container">
      <div class="row">
        <div class="col-main col-sm-9">
          <div class="page-title">
            <h1>Checkout</h1>
          </div>
          <ol class="one-page-checkout" id="checkoutSteps">
            <li id="opc-billing" class="section allow active">
              <div class="step-title"> <span class="number">1</span>
                <h3>Checkout Method</h3>
              </div>
              <div id="checkout-step-billing" class="step a-item" >
                <form id="co-billing-form" method="post">
                  <select name="user" style="visibility: hidden;" class="form-control" id="id_user">
                    <option value="{{request.user.id}}">{{request.user.email}}</option>
                  
                  </select>
                  
                  {% csrf_token %}
                  <fieldset class="group-select">
                    <ul>

                      <li id="billing-new-address-form" style="display: block;">
                        <fieldset>
                          <legend>New Address</legend>
                          <input type="hidden" name="" value="4269" id="billing:address_id">
                          <ul>
                            <li>
                              <div class="customer-name">
                                <div class="input-box name-firstname">
                                  <label for="billing:firstname"> First Name <span class="required">*</span> </label>
                                  <br>
                                  {{form.first_name}}
                                  {{form.errors.first_name}}
                                </div>
                                <div class="input-box name-lastname">
                                  <label for="billing:lastname"> Last Name <span class="required">*</span> </label>
                                  <br>
                                  {{form.last_name}}
                                  {{form.errors.last_name}}
                                </div>
                              </div>
                            </li>
                            <li>
                              <label>Address <span class="required">*</span></label>
                              <br>
                              {{form.address}}
                              {{form.errors.address}}
                            </li>
                            <li>
                            </li>
                            <li>
                              <div class="input-box">
                                <label for="billing:city">City <span class="required">*</span></label>
                                <br>
                                {{form.city}}
                                {{form.errors.city}}
                              </div>
                              <div class="input-box">
                                <label for="billing:country_id">Country <span class="required">*</span></label>
                                <br>
                                {{form.country}}
                                {{form.errors.country}}
                              </div>
                            </li>
                            <li>
                              <div class="input-box">
                                <label for="billing:postcode">Zip/Postal Code <span class="required">*</span></label>
                                <br>
                                {{form.zipcode}}
                                {{form.zipcode.errors}}
                              </div>
                              <div class="input-box">
                                <label for="billing:telephone">Telephone <span class="required">*</span></label>
                                <br>
                                {{form.phone}}
                                {{form.phone.errors}}
                              </div>
                            </li>
                            <li>
                              {{form.is_default}}

                            </li>
                          </ul>
                        </fieldset>
                      </li>

                    </ul>
                    <p class="require"><em class="required">* </em>Required Fields</p>
                    {{form.errors}}
                    <button type="submit" class="button continue" ><span>Continue</span></button>
                  </fieldset>
                </form>
              </div>
            </li>
            
          </ol>
        </div>
        <aside class="col-right sidebar col-sm-3">
          <div class="block block-progress">
            <div class="block block-cart">
              <div class="block-title ">My Cart</div>
              <div class="block-content">

            </div>
            </div>
          </div>
        </aside>
      </div>
    </div>
  </section>
  <!-- Main Container End --> 
  

{% endblock content %}
  

{% block js %}
<!-- JavaScript --> 
<script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.flexslider.js' %}"></script>
<script type="text/javascript" src="{% static 'js/cloud-zoom.js' %}"></script>
{% endblock js %}

checkout/templates/checkout_billing_info.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Checkout billing Information{% endblock title %}

{% block css %}
<!-- CSS Style -->
<link rel="stylesheet" type="text/css" href="{% static 'css/internal.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/flexslider.css' %}">
{% endblock css %}


  {% block content %}
  <!-- Main Container -->
  <section class="main-container col2-right-layout bounceInUp animated">
    <div class="main container">
      <div class="row">
        <div class="col-main col-sm-9">
          <div class="page-title">
            <h1>Checkout</h1>
          </div>
          <ol class="one-page-checkout" id="checkoutSteps">
            <li id="opc-login" class="section">
              <div class="step-title"> <span class="number">1</span>
                <h3 class="one_page_heading">Checkout Method</h3>
                <!--<a href="#">Edit</a>--> 
              </div>
            </li>
            <li id="opc-billing" class="section allow active">
              <div class="step-title"> <span class="number">2</span>
                <h3 class="one_page_heading">Billing Information</h3>
                <!--<a href="#">Edit</a>--> 
              </div>
              <div id="checkout-step-billing" class="step a-item">
                <form id="co-billing-form" action="" method="post">

                  {% csrf_token %}
                  <fieldset class="group-select">
                    <select name="user" class="form-control" style="visibility: hidden;" id="id_user">                    
                      <option value="{{request.user.id}}">{{request.user.email}}</option>
                    
                    </select>
                    <ul>
                      <li id="billing-new-address-form">
                        <fieldset>
                          <legend>New Address</legend>
                          <input type="hidden"  id="billing:address_id" />
                          <ul>
                            <li>
                              <div class="customer-name">
                                <div class="input-box name-firstname">
                                  <label for="billing:firstname"> First Name<span class="required">*</span></label>
                                  <br />
                                  <!-- <input type="text" id="billing:firstname" name="" title="First Name" class="input-text" /> -->
                                  {{form.first_name}}
                                </div>
                                <div class="input-box name-lastname">
                                  <label for="billing:lastname"> Last Name<span class="required">*</span> </label>
                                  <br />
                                  <!-- <input type="text" id="billing:lastname" name="" title="Last Name" class="input-text" /> -->
                                  {{form.last_name}}
                                </div>
                              </div>
                            </li>
                            <!-- <li>
                              <div class="input-box">
                                <label for="billing:company">Company</label>
                                <br />
                                <input type="text" id="billing:company" name="" title="Company" class="input-text" />
                              </div>
                              <div class="input-box">
                                <label for="billing:email">Email Address <span class="required">*</span></label>
                                <br />
                                <input type="text" name="billing[email]" id="billing:email" title="Email Address" class="input-text" />
                              </div>
                            </li> -->
                            <li>
                              <label for="billing:street1">Address <span class="required">*</span></label>
                              <br />
                              <!-- <input type="text" title="Street Address" name="" id="billing:street1  street1" class="input-text" /> -->
                              {{form.address}}
                            </li>
                            <!-- <li>
                              <input type="text" title="Street Address 2" name="" id="billing:street2 street2" class="input-text" />
                            </li> -->
                            <li>
                              <div class="input-box">
                                <label for="billing:city">City <span class="required">*</span></label>
                                <br />
                                <!-- <input type="text" title="City" name="" class="input-text" id="billing:city" /> -->
                                {{form.city}}
                              </div>
                              <div class="input-box">
                                <label for="billing:country">Country <span class="required">*</span></label>
                                <br />
                                <!-- <input type="text" title="City" name="" class="input-text" id="billing:city" /> -->
                                {{form.country}}
                              </div>
                              <!-- <div id="div" class="input-box">
                                <label for="billing:region">State/Province <span class="required">*</span></label>
                                <br />
                                <select defaultvalue="" id="billing:region_id" name="" title="State/Province" class="validate-select">
                                  <option>Please select region, state or province</option>
                                  <option value="1">Alabama</option>
                                  <option value="2">Alaska</option>
                                  <option value="3">American Samoa</option>
                                </select>
                              </div> -->
                            </li>
                            <li>
                              <div class="input-box">
                                <label for="billing:telephone">Telephone <span class="required">*</span></label>
                                <br />
                                <input type="text" name="" title="Telephone" class="input-text" id="billing:telephone" />
                              </div>
                              <div class="input-box">
                                <label for="billing:zip">Zip Code</label>
                                <br />
                                <!-- <input type="text" name="" title="Fax" class="input-text" id="billing:fax" /> -->
                                {{form.zipcode}}
                              </div>
                            </li>
                            
                              <input type="hidden" name="" value="1" />
                            </li>
                          </ul>
                        </fieldset>
                      </li>
                      
                    </ul>
                    <p class="require"><em class="required">* </em>Required Fields</p>
                    <button type="submit" class="button continue confirmOrder" ><span>Confirm order</span></button>
                    <br>
                    <br>
                    <br>
                    <div id="paypal-button-container" style="display: none;"></div>

                  </fieldset>
                </form>
              </div>
            </li>
          </ol>
        </div>
        <aside class="col-right sidebar col-sm-3">
          <div class="block block-progress">
            <div class="block block-cart">
              <div class="block-title ">My Cart</div>

            </div>
            </div>
          </div>
        </aside>
      </div>
    </div>
  </section>
  <!-- Main Container end --> 
  

  {% endblock content %}
  
  {% block js %}

  <script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.flexslider.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/cloud-zoom.js' %}"></script>
  {% endblock js %}
  